base_config:
  - ./sr_base.yaml
  - ./df2k4x.yaml
trainer_cls: tasks.rrdb.RRDBSatTask
# model
hidden_size: 64
lr: 0.0002
num_block: 15

# train and eval
max_updates: 400000
valid_steps: 3
save_ckpt_interval: 20000
val_check_interval: 25000
max_s2_images: 1
loss_type: l1
